name: Cypress

on:
  pull_request:
  push:
    branches:
      - main
      - master
      - stable*

env:
  BRANCH: ${{ github.base_ref || github.event.repository.default_branch }}

jobs:
  cypress-e2e:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # run multiple copies of the current job in parallel
        containers: [1]

    name: e2e runner ${{ matrix.containers }}
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v3.5.2

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@v2.2 # v2.1
        id: versions
        with:
          fallbackNode: '^20'
          fallbackNpm: '^9'

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v3
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Pull server image
        run: docker pull ghcr.io/nextcloud/continuous-integration-shallow-server

      - name: Run E2E cypress tests
        uses: cypress-io/github-action@1b70233146622b69e789ccdd4f9452adc638d25a # v6.6.1
        with:
          # cypress io
          record: true
          parallel: true
          # cypress env
          ci-build-id: ${{ github.sha }}-${{ github.run_number }}
          tag: ${{ github.event_name }}
          group: 'E2E'
          # Build library before using it
          build: npm run build:instrumented
        env:
          # Needs to be prefixed with CYPRESS_
          CYPRESS_BRANCH: ${{ env.BRANCH }}
          # https://github.com/cypress-io/github-action/issues/124
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Collect coverage
        uses: codecov/codecov-action@v4.3.0
        with:
          files: ./coverage/lcov.info

  cypress-component:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        # run multiple copies of the current job in parallel
        containers: [1]

    name: component runner ${{ matrix.containers }}
    steps:
      - name: Checkout
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v3.5.2

      - name: Read package.json node and npm engines version
        uses: skjnldsv/read-package-engines-version-actions@v2.2 # v2.1
        id: versions
        with:
          fallbackNode: '^20'
          fallbackNpm: '^9'

      - name: Set up node ${{ steps.versions.outputs.nodeVersion }}
        uses: actions/setup-node@60edb5dd545a775178f52524783378180af0d1f8 # v3
        with:
          node-version: ${{ steps.versions.outputs.nodeVersion }}

      - name: Set up npm ${{ steps.versions.outputs.npmVersion }}
        run: npm i -g npm@"${{ steps.versions.outputs.npmVersion }}"

      - name: Run Components cypress tests
        uses: cypress-io/github-action@1b70233146622b69e789ccdd4f9452adc638d25a # v6.6.1
        with:
          # to run component tests we need to use "component: true"
          component: true
          # cypress io
          record: true
          parallel: true
          # cypress env
          ci-build-id: ${{ github.sha }}-${{ github.run_number }}
          tag: ${{ github.event_name }}
          group: 'Components'
          # Tests use (instrumented) built files
          build: npm run build:instrumented
        env:
          # Needs to be prefixed with CYPRESS_
          CYPRESS_BRANCH: ${{ env.BRANCH }}
          # https://github.com/cypress-io/github-action/issues/124
          COMMIT_INFO_MESSAGE: ${{ github.event.pull_request.title }} 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}

      - name: Collect coverage
        uses: codecov/codecov-action@84508663e988701840491b86de86b666e8a86bed # v4.3.0
        with:
          files: ./coverage/lcov.info

  summary:
    runs-on: ubuntu-latest
    needs: [cypress-e2e, cypress-component]
    if: always()

    name: cypress-summary
    steps:
      - name: Summary status
        run: if ${{ (needs.cypress-e2e.result != 'success' && needs.cypress-e2e.result != 'skipped') || (needs.cypress-component.result != 'success' && needs.cypress-component.result != 'skipped') }}; then exit 1; fi
